"""
schem_to_stl_gui.py
--------------------
Interfaccia grafica per convertire file .schem in .stl "pieni".
Utilizza il riempimento dei buchi per creare un blocco unico.

Dipendenze:
    pip install nbtlib numpy scipy
"""

import gzip
import io
import os
import struct
import threading
import tkinter as tk
from tkinter import filedialog, messagebox, ttk

import numpy as np
from scipy.ndimage import binary_fill_holes

try:
    import nbtlib
except ImportError:
    import sys
    print("Installa le dipendenze con:\n  pip install nbtlib numpy scipy")
    sys.exit(1)


# ─── Logica di conversione ─────────────────────────────────────────────────────

NON_SOLID_KEYWORDS = [
    "air", "water", "lava", "leaves", "glass", "torch", "sign",
    "banner", "carpet", "flower", "grass", "fern", "dead_bush",
    "sapling", "vine", "lily", "kelp", "seagrass", "bubble",
    "fire", "soul_fire", "snow_layer", "ladder", "rail",
    "redstone", "lever", "button", "pressure", "trapdoor",
    "door", "gate", "bars", "chain", "lantern", "campfire",
    "candle", "amethyst_cluster",
]

def is_solid(block_name: str) -> bool:
    name = block_name.lower().split(":")[-1]
    return not any(kw in name for kw in NON_SOLID_KEYWORDS)

def load_schem(path: str):
    try:
        data = nbtlib.load(path)
    except Exception:
        with open(path, "rb") as f:
            raw = f.read()
        decompressed = gzip.decompress(raw)
        data = nbtlib.load(fileobj=io.BytesIO(decompressed))

    root = data["Schematic"] if "Schematic" in data else data

    if "Blocks" in root:
        blocks_section = root["Blocks"]
        palette = blocks_section["Palette"]
        block_data = np.array(list(blocks_section["Data"]), dtype=np.int32)
    elif "Palette" in root:
        palette = root["Palette"]
        block_data = np.array(list(root["BlockData"]), dtype=np.uint8)
    else:
        raise ValueError("Formato .schem non riconosciuto.")

    width, height, length = int(root["Width"]), int(root["Height"]), int(root["Length"])
    id_to_name = {int(v): str(k) for k, v in palette.items()}
    block_ids = block_data.reshape((height, length, width))
    return block_ids, id_to_name, (width, height, length)

def get_solid_mask(block_ids, id_to_name, ignore_set, only_solid):
    height, length, width = block_ids.shape
    mask = np.zeros((height, length, width), dtype=bool)
    
    for bid, name in id_to_name.items():
        short = name.split(":")[-1].split("[")[0]
        if short in ignore_set or "air" in name.lower():
            continue
        if only_solid and not is_solid(name):
            continue
        mask[block_ids == bid] = True

    # --- RIEMPIMENTO PER BLOCCO UNICO ---
    # Riempiamo tutti i buchi d'aria interni alla figura
    mask = binary_fill_holes(mask)
    return mask

FACE_NORMALS = [(0,1,0),(0,-1,0),(1,0,0),(-1,0,0),(0,0,1),(0,0,-1)]
FACE_QUADS = [
    [(0,1,0),(1,1,0),(1,1,1),(0,1,1)], [(0,0,1),(1,0,1),(1,0,0),(0,0,0)],
    [(1,0,0),(1,1,0),(1,1,1),(1,0,1)], [(0,0,1),(0,1,1),(0,1,0),(0,0,0)],
    [(0,0,1),(1,0,1),(1,1,1),(0,1,1)], [(1,0,0),(0,0,0),(0,1,0),(1,1,0)]
]
NEIGHBOR_OFFSETS = [(0,1,0),(0,-1,0),(1,0,0),(-1,0,0),(0,0,1),(0,0,-1)]

def generate_stl(mask, scale, output_path, progress_cb=None):
    triangles = []
    padded = np.pad(mask, 1, mode='constant', constant_values=False)
    solid_positions = np.argwhere(mask)
    total = len(solid_positions)

    for i, (y, z, x) in enumerate(solid_positions):
        for face_idx, (dy, dz, dx) in enumerate(NEIGHBOR_OFFSETS):
            # Crea la faccia solo se il vicino è aria (faccia esterna)
            if not padded[y+dy+1, z+dz+1, x+dx+1]:
                normal = FACE_NORMALS[face_idx]
                quad = FACE_QUADS[face_idx]
                v = [((x+qx)*scale, (y+qy)*scale, (z+qz)*scale) for (qx,qy,qz) in quad]
                triangles.append((normal, v[0], v[1], v[2]))
                triangles.append((normal, v[0], v[2], v[3]))
        if progress_cb and i % 5000 == 0:
            progress_cb(i / total)

    with open(output_path, "wb") as f:
        header = b"STL Solid Block Generated by Python" + b" " * 45
        f.write(header[:80])
        f.write(struct.pack("<I", len(triangles)))
        for (normal, v0, v1, v2) in triangles:
            f.write(struct.pack("<3f", *normal))
            for vert in (v0, v1, v2):
                f.write(struct.pack("<3f", *vert))
            f.write(struct.pack("<H", 0))

    if progress_cb: progress_cb(1.0)
    return len(triangles)


# ─── Interfaccia Tkinter ───────────────────────────────────────────────────────

class App(tk.Tk):
    BG      = "#0f0f13"
    SURFACE = "#1a1a24"
    BORDER  = "#2e2e42"
    ACCENT  = "#7c5cfc"
    TEXT    = "#e2e2f0"
    MUTED   = "#6b6b8a"
    SUCCESS = "#34d399"
    ERROR   = "#f87171"

    def __init__(self):
        super().__init__()
        self.title("Schem → STL Solid Converter")
        self.configure(bg=self.BG)
        self.resizable(False, False)

        self.input_path  = tk.StringVar()
        self.output_path = tk.StringVar()
        self.scale_var   = tk.StringVar(value="1.0")
        self.ignore_var  = tk.StringVar()
        self.only_solid  = tk.BooleanVar(value=True)
        self.status_var  = tk.StringVar(value="Pronto per la conversione solida.")
        self.progress    = tk.DoubleVar(value=0.0)
        self._running    = False

        self._build_ui()
        self._center()

    def _center(self):
        self.update_idletasks()
        w, h = self.winfo_width(), self.winfo_height()
        sw, sh = self.winfo_screenwidth(), self.winfo_screenheight()
        self.geometry(f"{w}x{h}+{(sw-w)//2}+{(sh-h)//2}")

    def _frame(self, parent, **kw):
        return tk.Frame(parent, bg=self.SURFACE, highlightbackground=self.BORDER, highlightthickness=1, **kw)

    def _label(self, parent, text, color=None, size=10, bold=False):
        return tk.Label(parent, text=text, bg=self.SURFACE, fg=color or self.TEXT, font=("Consolas", size, "bold" if bold else "normal"))

    def _entry(self, parent, textvariable, width=40):
        return tk.Entry(parent, textvariable=textvariable, bg="#0f0f13", fg=self.TEXT, insertbackground=self.TEXT, relief="flat", font=("Consolas", 10), width=width, highlightbackground=self.BORDER, highlightcolor=self.ACCENT, highlightthickness=1)

    def _button(self, parent, text, command, accent=False, width=None):
        bg = self.ACCENT if accent else self.SURFACE
        btn = tk.Button(parent, text=text, command=command, bg=bg, fg=self.TEXT, activebackground="#9d7dfe", activeforeground=self.TEXT, relief="flat", cursor="hand2", font=("Consolas", 10, "bold" if accent else "normal"), padx=12, pady=6, highlightbackground=self.BORDER, highlightthickness=1)
        if width: btn.config(width=width)
        btn.bind("<Enter>", lambda e: btn.config(bg="#9d7dfe" if accent else self.BORDER))
        btn.bind("<Leave>", lambda e: btn.config(bg=bg))
        return btn

    def _build_ui(self):
        P = 18
        hdr = tk.Frame(self, bg=self.BG)
        hdr.pack(fill="x", padx=P, pady=(P, 0))
        tk.Label(hdr, text="⬡  SCHEM → STL SOLID", bg=self.BG, fg=self.ACCENT, font=("Consolas", 18, "bold")).pack(side="left")
        
        tk.Frame(self, bg=self.BORDER, height=1).pack(fill="x", padx=P, pady=(10, 0))

        fi = self._frame(self)
        fi.pack(fill="x", padx=P, pady=(12, 0), ipady=8, ipadx=8)
        self._label(fi, "INPUT", color=self.MUTED, size=9, bold=True).grid(row=0, column=0, sticky="w", padx=8)
        self._entry(fi, self.input_path, width=52).grid(row=1, column=0, columnspan=2, padx=(8, 4), pady=4)
        self._button(fi, "📂 Sfoglia", self._pick_input).grid(row=1, column=2, padx=(0, 8))
        self.dims_label = self._label(fi, "", color=self.MUTED, size=9)
        self.dims_label.grid(row=2, column=0, columnspan=3, sticky="w", padx=8)

        fo = self._frame(self)
        fo.pack(fill="x", padx=P, pady=(10, 0), ipady=8, ipadx=8)
        self._label(fo, "OUTPUT STL", color=self.MUTED, size=9, bold=True).grid(row=0, column=0, sticky="w", padx=8)
        self._entry(fo, self.output_path, width=52).grid(row=1, column=0, columnspan=2, padx=(8, 4), pady=4)
        self._button(fo, "💾 Salva", self._pick_output).grid(row=1, column=2, padx=(0, 8))

        fopt = self._frame(self)
        fopt.pack(fill="x", padx=P, pady=(10, 0), ipady=8, ipadx=8)
        self._label(fopt, "SCALA (mm/blocco):").grid(row=1, column=0, padx=8)
        self._entry(fopt, self.scale_var, width=7).grid(row=1, column=1, sticky="w")
        tk.Checkbutton(fopt, text="Solo solidi", variable=self.only_solid, bg=self.SURFACE, fg=self.TEXT, selectcolor=self.BG, activebackground=self.SURFACE).grid(row=1, column=2, padx=20)

        style = ttk.Style()
        style.theme_use("default")
        style.configure("Dark.Horizontal.TProgressbar", troughcolor=self.BORDER, background=self.ACCENT, thickness=8)
        ttk.Progressbar(self, variable=self.progress, style="Dark.Horizontal.TProgressbar", maximum=1.0).pack(fill="x", padx=P, pady=(14, 0))

        bf = tk.Frame(self, bg=self.BG)
        bf.pack(fill="x", padx=P, pady=(10, P))
        self.convert_btn = self._button(bf, "▶ CONVERTI IN BLOCCO UNICO", self._run_conversion, accent=True, width=28)
        self.convert_btn.pack(side="left")
        self.status_lbl = tk.Label(bf, textvariable=self.status_var, bg=self.BG, fg=self.MUTED, font=("Consolas", 9), anchor="w")
        self.status_lbl.pack(side="left", padx=14)

    def _pick_input(self):
        path = filedialog.askopenfilename(filetypes=[("Sponge Schematic", "*.schem")])
        if path:
            self.input_path.set(path)
            self.output_path.set(os.path.splitext(path)[0] + "_solid.stl")
            try:
                block_ids, id_to_name, (w, h, l) = load_schem(path)
                self.dims_label.config(text=f"Struttura: {w}x{h}x{l}", fg=self.SUCCESS)
            except Exception as e: self.dims_label.config(text=str(e), fg=self.ERROR)

    def _pick_output(self):
        path = filedialog.asksaveasfilename(defaultextension=".stl")
        if path: self.output_path.set(path)

    def _run_conversion(self):
        if self._running: return
        self._running = True
        self.convert_btn.config(state="disabled")
        
        def worker():
            try:
                self.status_var.set("Caricamento...")
                block_ids, id_to_name, _ = load_schem(self.input_path.get())
                self.status_var.set("Riempimento volumi...")
                mask = get_solid_mask(block_ids, id_to_name, set(), self.only_solid.get())
                self.status_var.set("Generazione STL...")
                tri = generate_stl(mask, float(self.scale_var.get()), self.output_path.get(), self.progress.set)
                self.status_var.set(f"✅ Fatto: {tri:,} triangoli")
            except Exception as e:
                self.status_var.set(f"❌ Errore: {e}")
            finally:
                self._running = False
                self.convert_btn.config(state="normal")

        threading.Thread(target=worker, daemon=True).start()

if __name__ == "__main__":
    App().mainloop()